language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - python requirements.py
  - pip install codecov coveralls
  - python setup.py install

script:
  - coverage run --m tests
  # exclude bootstrap for ast transformations cannot be detected by coverage, causing incorrect report.
  - coverage report

after_success:
  - codecov
  - coveralls